spring.application.name=SpringBootBookManage9135
server.port=8081
server.servlet.context-path=/SpringBootBookManage9135
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
Spring.datasource.url=jdbc:mysql://localhost:3306/bookmanage?useUnicode==ture&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
Spring.datasource.username=wu
Spring.datasource.password=699576
Spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
Spring.datasource.druid.initial-size=20
Spring.datasource.druid.minIdle=10
Spring.datasource.druid.maxActive=100
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.hstc.SpringBootBookManage9135.entity
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
spring.profiles.active=dev
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
logging.level.root=info
spring.jmx.enabled=true
